#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: $0 <day>"
  exit 1
fi

DAY=$(printf "%02d" $1)
URL="https://adventofcode.com/2024/day/$((10#$1))/input"
COOKIE="53616c7465645f5fe132c10c3f558dc813162cb5f01995686fec95d17d4154d0bc3f9e2da636b63547ca2136ac9479d6f52446f1bba10b66d6ad8cebbe7160a4"

DIR="day${DAY}"

curl --cookie "session=$COOKIE" "$URL" -o "${DIR}/input.txt"
echo "Fetched URL: $URL"